url: https://appship.github.io/port
# baseurl: /
# Site settings
title: the AppShip
email: firstofficer@appship.com
description: "This is the homepage of the AppShip, Inc. We are a full service design and development consultancy, or dev shop if you will. We believe in supporting the growth of under-represented technologists while creating beautifully designed and developed applications. Our teams are lead by experienced leads overseeing our classes of apprentices. We build apps, through our apprenticeship, then we ship em."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
# people:
# - name: JT Stuart
#   pic: 1
#   position: Lead Designer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: stack-overflow
#       url: #

# - name: Larry Parker
#   pic: 2
#   position: Lead Marketer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: linkedin
#       url: #

# - name: Diana Petersen
#   pic: 3
#   position: Lead Developer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: google-plus
#       url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/appshipcrew
  - title: facebook
    url: https://www.facebook.com/appship/
  - title: github
    url: http://github.com/appship

# Postal address (add as many lines as necessary)
address:
  - line: 495 Fulton Street
  - line: San Francisco, CA 94102

# Build settings
markdown: kramdown
permalink: pretty